/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "nc-primary": "#03241a",
        "nc-primary-container": "#1b3a2f",
        "nc-on-primary": "#ffffff",
        "nc-on-primary-container": "#83a496",
        "nc-secondary": "#994621",
        "nc-secondary-container": "#ff9569",
        "nc-on-secondary": "#ffffff",
        "nc-on-secondary-container": "#762c07",
        "nc-tertiary": "#112316",
        "nc-tertiary-container": "#26382b",
        "nc-on-tertiary": "#ffffff",
        "nc-on-tertiary-container": "#8da290",
        "nc-surface": "#faf9f6",
        "nc-surface-dim": "#dbdad7",
        "nc-surface-bright": "#faf9f6",
        "nc-surface-container-lowest": "#ffffff",
        "nc-surface-container-low": "#f4f3f1",
        "nc-surface-container": "#efeeeb",
        "nc-surface-container-high": "#e9e8e5",
        "nc-surface-container-highest": "#e3e2e0",
        "nc-surface-variant": "#e3e2e0",
        "nc-on-surface": "#1a1c1a",
        "nc-on-surface-variant": "#414845",
        "nc-outline": "#727974",
        "nc-outline-variant": "#c1c8c3",
        "nc-error": "#ba1a1a",
        "nc-on-error": "#ffffff",
        "nc-error-container": "#ffdad6",
        "nc-on-error-container": "#93000a",
        "nc-inverse-surface": "#2f312f",
        "nc-inverse-on-surface": "#f2f1ee",
        "nc-inverse-primary": "#accebf",
        "nc-surface-tint": "#456558",
        "nc-background": "#faf9f6",
      },
      fontFamily: {
        headline: ["var(--font-playfair)", "Playfair Display", "serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: ["light"],
  },
};
